services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_HOST
        value: n8n-33tp.onrender.com
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://n8n-33tp.onrender.com/
      - key: GENERIC_TIMEZONE
        value: Asia/Shanghai

      # Supabase 数据库配置
      - key: DB_TYPE
        value: postgres
      - key: DB_POSTGRESDB_HOST
        value: eiyaloehytwaralfqsrk.supabase.co
      - key: DB_POSTGRESDB_PORT
        value: 5432
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_USER
        value: postgres
      - key: DB_POSTGRESDB_PASSWORD
        value: 310107200710234434
