services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: N8N_PORT
        value: ${PORT}
      - key: N8N_HOST
        value: your-n8n-app.onrender.com   # 这里改成你的 Render 域名
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://your-n8n-app.onrender.com/   # 改成你的域名
      - key: GENERIC_TIMEZONE
        value: Asia/Shanghai   # 你在国内可以设置上海时区
